AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Distributes organization donations
Parameters:
  MongoUri:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/api/db/mongo_uri'
Resources:
  OrgDistributeDonationsDeadLetterQueue:
    Type: AWS::SQS::Queue
  OrgDistributeDonationsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: org-distribute-donations-input
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt OrgDistributeDonationsDeadLetterQueue.Arn
        maxReceiveCount: 3
      VisibilityTimeout: 960
  OrgDistributeDonationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 2048
      Timeout: 900
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: ./
      Events:
        OrgDistributeDonationsEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt OrgDistributeDonationsQueue.Arn
            BatchSize: 1
      Policies:
        - AmazonSQSFullAccess
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
        - Statement:
          - Effect: Allow
            Action:
              - 'kms:Decrypt'
              - 'kms:ListKeys'
            Resource: '*'
      Environment:
        Variables:
          MONGO_URI: !Ref MongoUri
